#!/usr/bin/env bash
# Displays information about a domain and/or its subdomains.
display ()
{
    path=$1.$2
    OUTPUT="$(dig $path | grep -A1 'ANSWER SECTION:' | tail -1)"
    echo "$OUTPUT"
}
if [[ $# == 2 ]]; then
    path=$2.$1
    dig "$path" | grep -A1 'ANSWER SECTION:' | tail -1
elif [[ $# == 1 ]]; then
    subdomains=('www', 'lb-01', 'web-01', 'web-02')
    for i in "${subdomains[@]}"
    do
	display $i $1
    done
else
    exit 0
fi
