#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
new_config="\trewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
conf_file="/etc/nginx/sites-enabled/default"
server="0,/server\s+\{/s//& \n"
sudo sed -i -E "${server}${new_config}/" $conf_file
sudo service nginx start
