#!/usr/bin/env bash
# Handle start, restart and stop options on manage_my_process process.
# shellcheck disable=SC2086
fn="/var/run/my_process.pid"
pid="$(pgrep -f ./manage_my_process)"
case "$1" in
    start)
        ./manage_my_process &
        echo "$pid" > $fn
        echo "manage_my_process started"
        ;;
    stop)
        kill $pid
        sudo rm -rf $fn
        echo "manage_my_process stopped"
        ;;
    restart)
        kill $pid
        sudo rm -rf $fn
        ./manage_my_process &
        echo "$pid" > $fn
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac