#!/usr/bin/env bash
# A script that displays Holberton School 10 times and at index 9 adds 'Hi'.
i=0
while ((i<10));do
    if ((i==9));then
	echo "Hi"
    fi
    echo "Holberton School"
    ((i++))
done
