#!/usr/bin/env bash
# Running Nginx as nginx user and listening on all active IPS on port 8080
sudo pkill apache2
sudo chmod 744 /etc/nginx/nginx.conf
sed -i '2i, user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo su nginx -c "service nginx start"
