#!/usr/bin/env bash
# creates an RSA key pair (name of the created private key must be holberton,
# number of bits in the key is 4096 and the passphrase must be betty.
ssh-keygen -b 4096 -f holberton -N betty
